### PR TITLE
#566

### PR DESCRIPTION
**Pull request by NitinMadhukar**
* **Please check if the PR fulfills these requirements**
- [1 ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ 1] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**

improved the layout

* **Does this PR introduce a breaking change?**

yes

* **Preview / Steps to verify your work**:
just change few lines of code

### CODE REVIEW

**Comment by AakashMallik** [comment]
@NitinMadhukar What is this PR for?

**Comment by NitinMadhukar** [comment]
i have improved the  layout pages

**Comment by Dishebh** [comment]
@NitinMadhukar Pls mention the issue fix.

**Comment by NitinMadhukar** [comment]
@Dishebh updated layout

**Comment by AakashMallik** [comment]
@NitinMadhukar Not sure how am I supposed to review 3.5k lOC in a single PR.

**Pull request closed without merging**
