### PR TITLE
updated heading text

### PR DESCRIPTION
**Pull request by RishabhKodes**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ ] Feature implementation
- [x] Doc updates

* **What changes have you introduced?**

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Review by CloudyPadmal — COMMENTED** [review]
Hello @RishabhKodes , what does `(_ _)` do in JS?

**Comment by RishabhKodes** [comment]
> Hello @RishabhKodes , what does `(_ _)` do in JS?

Nothing, just kept the brackets and the underscore there to differentiate the technical details from the normal details in About Us.

**Review by orangecms — CHANGES_REQUESTED** [review]
Thank you for your PR!

This text  is about the general project goals and scope, so implementation details of a specific app should be documented in the specific respository's README (see the draft PR #617 ) and/or the [PSLab documentation](https://github.com/fossasia/pslab-documentation). If you could help out there, that would be great, especially with the documentation of the software stack. Currently missing, for example, is the setup of the UI, based on Material and a bit of customization.

**Comment by RishabhKodes** [comment]
> Thank you for your PR!
> 
> This text is about the general project goals and scope, so implementation details of a specific app should be documented in the specific respository's README (see the draft PR #617 ) and/or the [PSLab documentation](https://github.com/fossasia/pslab-documentation). If you could help out there, that would be great, especially with the documentation of the software stack. Currently missing, for example, is the setup of the UI, based on Material and a bit of customization.

Sure! Working on it

**Comment by orangecms** [comment]
We have set up Storybook now with support for Markdown. Please check out the current development branch and see the [upstream docs](https://storybook.js.org/docs/react/api/mdx) for details. That would be a suitable place if you would like to contribute the UI component documentation. Closing this PR now. Please file a new one then. Thank you! :)

**Pull request closed without merging**
