### PR TITLE
[#323] switch added for pulse section

### PR DESCRIPTION
**Pull request by ojasgulati**
Fixes #328 
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates
* **What changes have you introduced?**
Switch added for pulse section inside multimeter component.

* **Does this PR introduce a breaking change?**
NO

* **Preview / Steps to verify your work**:
Go to multimeter component and verify the switch whether it is working or not correctly.

image

### CODE REVIEW

**Comment by AakashMallik** [comment]
@ojasgulati Please add snapshots of your UI related work. It would make the review job faster.

**Comment by AakashMallik** [comment]
This needs changes... will suggest in a sec.

**Comment by ojasgulati** [comment]
> @ojasgulati Please add snapshots of your UI related work. It would make the review job faster.

sure

**Comment by AakashMallik** [comment]
>     * **Please check if the PR fulfills these requirements**
> 
> 
>     * [x]  The commit message follows our guidelines
> 
>     * [ ]  Tests for the changes have been added (for bug fixes / features)
> 
>     * [ ]  Docs have been added / updated (for bug fixes / features)
> 
> 
>     * **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
> 
> 
>     * [ ]  Bug fix
> 
>     * [x]  Feature implementation
> 
>     * [ ]  Doc updates
> 
> 
>     * **What changes have you introduced?**
>       Switch added for pulse section inside multimeter component.
> 
>     * **Does this PR introduce a breaking change?**
>       NO
> 
>     * **Preview / Steps to verify your work**:
>       Go to multimeter component and verify the switch whether it is working or not correctly.
> 
> 
> image

Also mention the issue number that this PR fixes like I have mentioned on my PR

**Comment by AakashMallik** [comment]
Look for these functions in Multimeter.py to get a clearer picture

```python
    def capture_loop(self):
        self.is_reading = True
        while self.is_reading:
            if self.active_catagory == 'VOLTAGE':
                self.read_voltage(self.active_subtype)
            elif self.active_catagory == 'PULSE':
                self.read_pulse(self.active_subtype, self.parameter)
            elif self.active_catagory == 'MISC':
                self.read_misc(self.active_subtype)
```

```python
def read_pulse(self, pin_name, reading_type):
        if reading_type == 'PULSE_COUNT':
            self.device.countPulses(pin_name)
            time.sleep(1)
            data = self.device.readPulseCount()
        elif reading_type == 'PULSE_FREQUENCY':
            data = self.device.get_freq(pin_name)
            time.sleep(0.25)
        output = {'type': 'START_MUL_MET', 'data': data}
        print(json.dumps(output))
        sys.stdout.flush()
```

**Comment by ojasgulati** [comment]
I will look into it

**Comment by ojasgulati** [comment]
@AakashMallik if I use parameter logic of UI does not give me correct output.

**Comment by AakashMallik** [comment]
@ojasgulati Why is that so?

**Pull request closed without merging**
