### PR TITLE
[#446] Truncated file names now displayed in file viewer

### LINKED ISSUE #446: Show file name in data logger tabs
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
- For now only the instrument name is shown

* **What is the expected behavior?**
- File name should also be shown in the tabs, truncated if too long.

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #446 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
- File names now displayed in tabs in file viewer
- File names truncated if too long
- File name extractor moved to the utility file

* **Does this PR introduce a breaking change?**

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
In Android app we don't name the log files as `test.csv` etc. They are named `yyyy-MM-dd HH:mm:ss.SSS.csv`. Where are these logs coming from?

Also if we are going for a truncate, take the length of `yyyy-MM-dd HH:mm:ss.SSS.csv` as max length.

**Comment by AakashMallik** [comment]
> In Android app we don't name the log files as `test.csv` etc. They are named `yyyy-MM-dd HH:mm:ss.SSS.csv`. Where are these logs coming from?
> 
> Also if we are going for a truncate, take the length of `yyyy-MM-dd HH:mm:ss.SSS.csv` as max length.

Marco sir, talked about the possibility of renaming the data files, so I was taking that as a possibility.
But this should not cause a problem as if the names are yyyy-MM-dd.csv it should still work, i mean, i wrote it to be flexible. I will make the change to truncate as u have asked ASAP. @CloudyPadmal

**Comment by AakashMallik** [comment]
> In Android app we don't name the log files as `test.csv` etc. They are named `yyyy-MM-dd HH:mm:ss.SSS.csv`. Where are these logs coming from?
> 
> Also if we are going for a truncate, take the length of `yyyy-MM-dd HH:mm:ss.SSS.csv` as max length.

Also, now that you have mentioned it, I think I will have to change my naming function... Will raise an issue soon. :sweat_smile:

**Comment by AakashMallik** [comment]
> In Android app we don't name the log files as `test.csv` etc. They are named `yyyy-MM-dd HH:mm:ss.SSS.csv`. Where are these logs coming from?
> 
> Also if we are going for a truncate, take the length of `yyyy-MM-dd HH:mm:ss.SSS.csv` as max length.

I have addressed the truncation length like you asked me to.

**Pull request merged**
