### PR TITLE
revert start script to d95758cddb4abb060ade7feb9eab68f373a8b1db~1

### PR DESCRIPTION
**Pull request by orangecms**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**

fixed the start script for development, see also https://github.com/fossasia/pslab-desktop/commit/d95758cddb4abb060ade7feb9eab68f373a8b1db#r40330639

* **Does this PR introduce a breaking change?**

no

* **Preview / Steps to verify your work**:

`npm start`

### CODE REVIEW

**Comment by AakashMallik** [comment]
@orangecms Thanks for the prompt response.

**Comment by AakashMallik** [comment]
Wait a sec, my write access has been revoked!! WTH!!
This better be a glitch.

**Comment by orangecms** [comment]
cc @mariobehling

**Comment by mariobehling** [comment]
Thanks!

@AakashMallik Write access is usually removed if devs dont involve or contributor code for some time, months or longer. This is nothing specifically to your account and we have not looked at your account in particular. This was probably done when we reviewed activity in the project and who currently has write access. Everyone can still make reviews.

Merging it.

**Pull request merged**
