### PR TITLE
[#384] Home component implemented

### LINKED ISSUE #384: Implement Tabs to Access Instruments as in Android App
The Android app already has designs and tabs for different instruments. Please reuse them and implement tabs on the main screen of the app.

Screenshot from 2019-06-19 18-25-44

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #384 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
- Implemented a new home-page
- Changed the theme of the app

* **Does this PR introduce a breaking change?**
NO

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by AakashMallik** [comment]
@akshatnit Sir, let me know your thoughts on this new Home Component for PSLab desktop

**Comment by kushthedude** [comment]
@AakashMallik The background looks a bit fancier than it should be.

**Comment by AakashMallik** [comment]
> IMO, the placements and positioning of elements are good. But, the colors are too fancy.
> 
>     * Use red(primary color for PSLab) background for the left navigation.
> 
>     * Limit the gradient background to single color, maybe white or light grey.

Sir the Red of PSLab is really ugly and it somewhat coincides with the error Red. :sob: Any suggestions as to how we should proceed with that?  @akshatnitd

**Comment by adityastic** [comment]
> Sir the Red of PSLab is really ugly 

I completely agree. Let me download the project and try to gather some opinions on what could be the best design

**Comment by AakashMallik** [comment]
> > Sir the Red of PSLab is really ugly
> 
> I completely agree. Let me download the project and try to gather some opinions on what could be the best design

There we go.. team work.. I like that.. @adityastic

**Comment by akshatnitd** [comment]
I know that, we anyhow need to use it as it the chosen theme color. Limit the use of red, whjch won't make it look ugly. Try the above suggestion and post a screenshot. Eg - Even YouTube has a red as primary color, but they use it very judiciously.

**Comment by AakashMallik** [comment]
> I know that, we anyhow need to use it as it the chosen theme color. Limit the use of red, which won't make it look ugly. Try the above suggestion and post a screenshot. Eg - Even YouTube has a red as primary color, but they use it very judiciously.

Aah.. right... That would be an interesting reference...  Thanks, sir.

**Comment by cweitat** [comment]
keep it simple. no red background. just a white background with icons, the instruments' border and title red.
description text remains as black

**Comment by AakashMallik** [comment]
> keep it simple. no red background. just a white background with icons, the instruments' border and instruments' title red.
> description text remains as black
> 
> Also, please fix conflicted file

That is a bit too simple for a modern app.. We are having an ongoing discussion, so hopefully, we'll settle down after things have been finalized by the team.

**Comment by mariobehling** [comment]
Please also keep the colors consistent. Don't use additional gradients. Just make the top bar red as in the Android app.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by AakashMallik** [comment]
> Please resolve conflicts.

Yes... This will be finished today.. I was fixing a few bugs yesterday so got caught up in that...  :innocent:

**Comment by AakashMallik** [comment]
Exactly the way android has it... Same colours this time, gradients removed, background simplified.

**Comment by CloudyPadmal** [comment]
We can have the same svg icons from Android repo for instruments

**Comment by mariobehling** [comment]
I am confused. The referenced issue is only about the home screen. We should follow up on other screens separately.

How can we make the home screen as much as possible as the Android app? E.g.:
* red tiles/badges
* white font
* the same icons 
* no Pocket science lab text

As much as possible as this one:
> view_instrument_panel

**Comment by AakashMallik** [comment]
@mariobehling @CloudyPadmal @cweitat 


- red background for cards
- more rounded badges
- same icons as android
- white text / white icons
- scrollable just as in android 
- no PSLab text

**Comment by mariobehling** [comment]
Thanks, we can follow up on this in more issues, e.g. compare this to landscape mode in Android. Anyways, let's move step by step.

**Comment by mariobehling** [comment]
Please don't merge your own commits.

**Pull request merged**
