### PR TITLE
[#492] Read button removed, record button shifted

### PR DESCRIPTION
**Pull request by AakashMallik**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
- Remove play button
- Auto data fetch for oscilloscope
- Record button shifted to app bar

* **Does this PR introduce a breaking change?**
- NO

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by mariobehling** [comment]
Please make the record button white and use the same button as in Android app.

**Comment by AakashMallik** [comment]
> Please make the record button white and use the same button as in Android app.

The button is white, while taking the screenshot it was disabled as I had no device connected to my laptop. I'll change the icon though. @mariobehling

**Comment by AakashMallik** [comment]
@neel1998 @mariobehling I just checked, android and desktop appear to be using the same icons for record button. Right?

**Comment by CloudyPadmal** [comment]
In Android there's a `REC` label underneath the icon

**Comment by AakashMallik** [comment]
> In Android there's a `REC` label underneath the icon

@CloudyPadmal @mariobehling I have modified the record button.. 

Changed both in multimeter and Oscilloscope 


Lemme know if this is fine.

**Pull request merged**
