### PR TITLE
Appbar implemented, device connectivity status indicator added, comms protocol improved

### LINKED ISSUE #243: Add an Appbar in Appshell for showing relevant information
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
No app bar as of now

* **What is the expected behaviour?**
An app bar should be created so that instrument cluster related information can be shown

* **Please tell us about your environment:**
  - OS with version number: Linux 18.04

* **Would you like to work on it?**
Yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #243

## Changes
- [x] Added an Appbar
- [x] Added connectivity status indicator and reconnect button
- [x] Modified python code to send connectivity status
- [x] Improved communication protocol between python script and electron app

### CODE REVIEW

**Comment by AakashMallik** [comment]
> Fix for power source:
> Screenshot from 2019-04-19 14-15-07

I'll look into this. CSS issues.. my bad

**Comment by AakashMallik** [comment]
> > Fix for power source:
> > Screenshot from 2019-04-19 14-15-07
> 
> I'll look into this. CSS issues.. my bad

I am opening a new issue for this. I have probably made too many changes in a single PR. Addressing this CSS issue in a different PR would be more manageable I guess. @fragm3

**Comment by fragm3** [comment]
@AakashMallik not a problem

**Comment by mariobehling** [comment]
Thanks. Please fix Travis in following PRs.

**Pull request merged**
