### PR TITLE
Added alt prop

### PR DESCRIPTION
**Pull request by Dishebh**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
Added alt prop to img tags so as to remove the jsx console errors.

* **Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by adityastic** [comment]
@Dishebh codacy

**Comment by Dishebh** [comment]
@adityastic Done

**Comment by Dishebh** [comment]
@adityastic I guess the pr is upto the standards. Can you pls tell why the Codacy is showing error? Thanks.

**Comment by adityastic** [comment]
@Dishebh you should be able to fix these lint errors with --fix flag

**Comment by Dishebh** [comment]
> @Dishebh you should be able to fix these lint errors with --fix flag

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

The error that it throws. What shall I do? Pls help

**Comment by AakashMallik** [comment]
@Dishebh The way I see it, you have just added an alt prop but no useful value. Could you please put in a little more work into this PR and add some relevant data in the alt props.
Thanks.

**Pull request merged**
