### PR TITLE
Use new oscilloscope backend

### PR DESCRIPTION
**Pull request by bessman**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
Change front end to use new oscilloscope back end. This PR goes together with https://github.com/fossasia/pslab-python/pull/129. Neither should be merged before both are ready.
This PR is ready for merge.

* **Does this PR introduce a breaking change?**
https://github.com/fossasia/pslab-python/pull/129 is a breaking change, which this PR fixes. 

* **Preview / Steps to verify your work**:
When this and https://github.com/fossasia/pslab-python/pull/129 are both used together, the front end should behave exactly like before.

### CODE REVIEW

**Comment by orangecms** [comment]
I'll try this out -- looks cleaner now from an API standpoint, thank you :)

**Comment by bessman** [comment]
That's the idea :) Among other things, it is no longer necessary to keep track of internal channel numbering. Just refer to the channel by name, and the back end will take care of the rest.

One change for the "worse" is that it is now necessary to keep track of how many samples you requested when using `capture_nonblocking`. It would be simple to keep track of that internally as well, but I expect most users will use `capture` rather than `capture_nonblocking`, and I'd rather not clutter up the back end with rarely used features unless absolutely necessary. What do you think?

**Comment by orangecms** [comment]
That sounds ok so far, though we might need something like a request ID (if we don't have it yet) to mitigate possible race conditions from quickly clicking around. That should be it, right?

**Comment by bessman** [comment]
Thought about it some more, decided that tracking number of samples internally is probably better after all.

You're right, we do need some way to prevent race conditions, but I don't think a request ID will be enough. We need to ensure that, once a capture call has been issued, no further capture calls are issued until the captured data has been fetched. Otherwise, even if we keep track of who requested what, the first caller will get faulty data because the ADC buffer has been overwritten.

I think semaphores are the way to go here, and I think it should be handled in the front end rather than the back end (since the back end is not threaded). Since the possibility of race conditions existed before this PR, let's handle that separately.

**Comment by bessman** [comment]
Actually, are race conditions even that big a problem? A user might manage to reconfigure an AnalogInput instance before it is used to scale incoming raw data, but that should only result in faulty data being displayed for a single frame. That doesn't seem serious enough to warrant the extra complexity needed to avoid it.

Could race conditions lead to other issues I'm not seeing?

**Pull request merged**
