### PR TITLE
[#417] Added FAQ and About us section

### PR DESCRIPTION
**Pull request by AakashMallik**
@mariobehling @cweitat @CloudyPadmal 

Fixes: #417 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ x Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
I have added an FAQ and About Us section same as android

* **Does this PR introduce a breaking change?**
No

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Let's get the list of link to bottom of the card view in about us page to fill out the page. May be if we can shrink the card from left and right that'll also do.

**Comment by AakashMallik** [comment]
> Let's get the list of link to bottom of the card view in about us page to fill out the page. May be if we can shrink the card from left and right that'll also do.

@CloudyPadmal

**Comment by cweitat** [comment]
> > Let's get the list of link to bottom of the card view in about us page to fill out the page. May be if we can shrink the card from left and right that'll also do.
> 
> @CloudyPadmal
> 

able to justify the text?

**Comment by AakashMallik** [comment]
> > > Let's get the list of link to bottom of the card view in about us page to fill out the page. May be if we can shrink the card from left and right that'll also do.
> > 
> > 
> > @CloudyPadmal
> > 
> 
> able to justify the text?

@cweitat 
photo6113821113780906455

Center justified just like the **android app**

**Pull request merged**
