### PR TITLE
upgraded concurrently package and fixed about page

### LINKED ISSUE #567: weird page responsiveness issue of about
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
Currently the application's about page has a weird responsiveness issue, where it decreses to a column of text with one one word per line if the screen is small
Also the image doesn't scale

* **If the current behavior is a bug, please provide the steps to reproduce it**
- Got to the about page
image

* **What is the expected behavior?**
it shouldn't really be like this and it should use the screen space provided

* **Please tell us about your environment:**
  - OS with version number: windows 1909

* **Would you like to work on it?**
Yes

### PR DESCRIPTION
**Pull request by Sid911**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) *this doesn't require a doc update*

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bug fix

* **What changes have you introduced?**
- fixes #567 
- Upgraded Concurrently package
- Fixed the UI responsiveness of about page

* **Does this PR introduce a breaking change?**
No

* **Preview / Steps to verify your work**:
**Before**
image

**After**
image

### CODE REVIEW

**Comment by Sid911** [comment]
@mariobehling please review this 😇

**Comment by Sid911** [comment]
someone.. this has been sitting for days 😅? @AakashMallik

**Comment by fcartegnie** [comment]
Why not just fixing the style in the style.js ?

**Comment by Sid911** [comment]
@fcartegnie I just wanted to override any styles being parented etc(if there any)... inline styling is supposed to do that... should I changed it in styles of Wrapper?

**Comment by fcartegnie** [comment]
> @fcartegnie I just wanted to override any styles being parented etc(if there any)... inline styling is supposed to do that... should I changed it in styles of Wrapper?
Just like CSS, style should be in a separate file

**Comment by Sid911** [comment]
sure its just a quick fix... @fcartegnie can you wait for a minute.. thanks 😇

**Comment by Sid911** [comment]
@fcartegnie Done.. can this be merged now 😄

**Pull request merged**
