### PR TITLE
Multimeter UI Completed

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #304 #305 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [x] Feature implementation
- [ ] Doc updates

* **What changes have you introduced?**
- Implemented the multimeter UI

* **Does this PR introduce a breaking change?**
No

* **Preview / Steps to verify your work**:

### CODE REVIEW

**Comment by mariobehling** [comment]
Please make the icons and text bigger. Could you make the circle and pointer look more like a real multimeter? Could we have something more similar to a real multimeter in general as well as the Android app?

pre112353_4211166

**Comment by AakashMallik** [comment]
> Please make the icons and text bigger. Could you make the circle and pointer look more like a real multimeter? Could we have something more similar to a real multimeter in general as well as the Android app?
> 
> pre112353_4211166

As for the fonts, the image that I have posted comes from a high-resolution screen, so the fonts look a little small due to high pixel density. But I am waiting for fellow contributors to convert the svg icnos to inline svg, then we can have a uniform size for everything. 
The dial that you are asking for is possible but that would need a bit of work and it would require use to create a custom dial, which will be a mini-project of its own. I will add these requirements to my bucket list and raise issues on this once we have the functionality part done. I hope that is okay. @mariobehling

**Comment by AakashMallik** [comment]
I'll make further modifications to the UI eventually. @CloudyPadmal @mariobehling

**Comment by mariobehling** [comment]
Ok, thanks. Following the UI that people are used to is very important for us. Cheers.

**Pull request merged**
