### PR TITLE
Add documentation for installing on Mac os

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bug fix
- [ ] Feature implementation
- [x] Doc updates

Issue fixed: #230

* **What changes have you introduced?**
Add Documentation for installing PSLad in Mac OS

* **Does this PR introduce a breaking change?**
No

* **Preview / Steps to verify your work**:
https://github.com/kumuditha-udayanga/pslab-desktop/blob/development/README.md

### CODE REVIEW

**Comment by kumuditha-udayanga** [comment]
@mariobehling @CloudyPadmal  It would be nice to have your reviews 😇

**Comment by mariobehling** [comment]
Can you confirm that it works for you? Do you have screenshots? As I am not on Mac, I cannot review this.

**Comment by kumuditha-udayanga** [comment]
> Can you confirm that it works for you? Do you have screenshots? As I am not on Mac, I cannot review this.
These are the screenshots

Screenshot 2020-01-20 at 22 38 24
Screenshot 2020-01-20 at 22 38 30
Screenshot 2020-01-20 at 22 35 42
Screenshot 2020-01-20 at 22 38 09

**Comment by kumuditha-udayanga** [comment]
@adityastic  Nice to have your reviews on this

**Pull request merged**
